### ISSUE TITLE
TypeError: Text.search() got multiple values for argument 'stopindex'

### ISSUE THREAD

**Issue by iprathammishra** [ChadiDridi/Python-IDE-Code#2]
## Problem Statement:
Hi! I found a ` TypeError ` in line 202 while running your file. 

## Solution:
Replacing line 202 with ` start = editor.search(tag, start, END, nocase=1) ` will make it work 👍

**Comment by ChadiDridi** [comment]
Thank you for the feedback ! It is fixed now.
